#!/usr/bin/perl -w

$fn = shift(@ARGV);

open IN, "< $fn";
open OUT, "> ontime-$fn";

while (<IN>) {

  print OUT;

  if (m/:init/) { last; }

}

while (<IN>) {
  print OUT;
  if (m/:goal/) { last; }

  if (m/at package([^ ]+)/) {
    print OUT "\t(still-on-time package$1)\n";
  }
}

while (<IN>) {
  if (m/at driver/ || m/at truck/) {
    chomp;
    print OUT "\t;$_; commented out\n"; 
  } else {
    print OUT;
  }
}

close IN;
close OUT;

