#!/usr/bin/perl -w

open DISP, "> dispscript";
open NODISP, "> nodispscript";

print DISP "#!/bin/bash\nulimit -t 60\n";
print NODISP "#!/bin/bash\nulimit -t 60\n";

for ($i = 1; $i <= 100; $i++) {
   system("./getgoaltimes-random-perturb ontime-pfile15 500plan $i");
   print DISP "./rewrite-no-lp --time-based-on-expansions-per-second 500 --include-metareasoning-time --multiply-TILs-by 1 --real-to-plan-time-multiplier 1 --calculate-Q-interval 100  --add-weighted-f-value-to-Q -0.000001 --min-probability-failure 0.001 --slack-from-heuristic --forbid-self-overlapping-actions --deadline-aware-open-list IJCAI --ijcai-gamma 1 --ijcai-t_u 100 --icaps-for-n-expansions 100 --use-dispatcher LPFThreshold --time-aware-heuristic 1 --dispatch-frontier-size 10 --subtree-focus-threshold 0.025 --dispatch-threshold 0.025 --optimistic-lst-for-dispatch-reasoning driverlogTimed.pddl withdeadlines-ontime-pfile15-$i > disp/15-$i\n";
   print NODISP "./rewrite-no-lp --time-based-on-expansions-per-second 500 --include-metareasoning-time --multiply-TILs-by 1 --real-to-plan-time-multiplier 1 --calculate-Q-interval 100  --add-weighted-f-value-to-Q -0.000001 --min-probability-failure 0.001 --slack-from-heuristic --forbid-self-overlapping-actions --deadline-aware-open-list IJCAI --ijcai-gamma 1 --ijcai-t_u 100 --icaps-for-n-expansions 100 --time-aware-heuristic 1 --dispatch-frontier-size 10 --subtree-focus-threshold 0.025 --dispatch-threshold 0.025 --optimistic-lst-for-dispatch-reasoning driverlogTimed.pddl withdeadlines-ontime-pfile15-$i > nodisp/15-$i\n";
}

close DISP;
close NODISP;

system("chmod 755 dispscript");
system("chmod 755 nodispscript");

