#!/usr/bin/perl -w

if (scalar(@ARGV) != 6) {
    print "Usage: getgoaltimes <domainfile> <ontime problem filename> <plan filename> <random seed> <at> <object>\n";
    exit(1);
}

$domainfile = shift(@ARGV);

if (!(-e $domainfile)) {
    print "$domainfile does not exist\n";
    exit(2);
}

$valstring = "./validate -t 0.001 -v $domainfile";

$problem = shift(@ARGV);
$plan = shift(@ARGV);
$seed = shift(@ARGV) + 0;
$at = shift(@ARGV);
$object = shift(@ARGV);

# first, we open the problem, and skip to the goals

open PROBLEM, "< $problem";

while (<PROBLEM>) {
    if (m/:goal/) { last; }
}

# ...then note what deadline Flag object had goals, and assume these were true at time zero

while (<PROBLEM>) {
    if (m/\($at ($object[^ ]+)/) {
       $goalattime{$1} = 0; # goalattime is a hash map, the key is the deadline Flag object goal, the value is 0
    }
}

close PROBLEM;

# run VAL, capture its output...
open IN, "$valstring $problem $plan |";

$timenow = 0;

while (<IN>) {
    # when val gets to the next action start/end, update $timenow
    if (m/Checking next happening \(time ([0-9\.]+)/) {
        $timenow = $1 + 0;
    }
    # then, if we see that a deadline Flag object has arrived, make a note of when this was
    if (m/Adding \($at ($object[^ ]+)/ && exists($goalattime{$1})) {
        $goalattime{$1} = $timenow;
    }
}

close IN;

open OUT, "> withdeadlines-$problem-$seed";
open PROBLEM, "< $problem";

# write everything up to the :init line to the output file
while (<PROBLEM>) {
    print OUT;
    if (m/:init/) { last; }
}

my @keyarray = (keys %goalattime);

my @sortedkeys = sort @keyarray;

open my $fh, '<', '/dev/urandom' or die "Unable to open /dev/urandom: $!";
read $fh, my $raw_seed, 4 or die "Unable to read from /dev/urandom: $!";
close $fh;

my $rseed = unpack 'L', $raw_seed; # 'L' is for a 32-bit unsigned integer
srand($rseed);

# ...then write the deadlines
foreach $flag (@sortedkeys) {
    $achievedat = $goalattime{$flag};
    if ($achievedat == 0) {
        print OUT "; The goal for $achievedat was achieved at time zero (in the initial state), so no deadline was generated\n";
    } else {
        $perturbment = rand(100) - 50;
        $achievedat = $achievedat + $perturbment; # add something between [-50,50) to the deadline
        print OUT "(at $achievedat (not (still-on-time $flag))) ; deadline on when $flag got to its goal location\n"
    }
}

# ...then write the rest
while (<PROBLEM>) { print OUT; }

close PROBLEM;
close OUT;
